[prune]
  go-tests = true
  unused-packages = true
  non-go = true

  [[prune.project]]
    name = "gopkg.in/src-d/go-git-fixtures.v3"
    non-go = false
    unused-packages = false

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "1.1.1"

[[constraint]]
  name = "github.com/google/go-github"
  version = "21.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/gregjones/httpcache"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.13.0"

[[constraint]]
  name = "gopkg.in/bblfsh/sdk.v1"
  version = "1.16.0"

[[constraint]]
  name = "gopkg.in/src-d/go-errors.v1"
  version = "1.0.0"

[[constraint]]
  name = "gopkg.in/src-d/go-git-fixtures.v3"
  version = "3.1.0"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.4.1"

[[constraint]]
  name = "gopkg.in/src-d/go-log.v1"
  version = "1.0.1"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[[constraint]]
  name = "gopkg.in/src-d/enry.v1"
  version = "1.6.4"

# go-queue does not work with the latest release, v1.2.0
[[constraint]]
  name = "github.com/satori/go.uuid"
  branch = "master"

[[constraint]]
  name = "gopkg.in/src-d/go-kallax.v1"
  version = "1.3.5"

[[constraint]]
  name = "gopkg.in/src-d/lookout-sdk.v0"
  version = "0.3.0"

[[constraint]]
  name = "github.com/sanity-io/litter"
  revision = "09e3a73d5b65eac2f14578aec8fb74ee9b4f1a5e"

[[constraint]]
  name = "github.com/bradleyfalzon/ghinstallation"
  version = "0.1.2"

[[constraint]]
  branch = "master"
  name = "github.com/src-d/lookout-test-fixtures"

[[constraint]]
  name = "gopkg.in/src-d/go-queue.v1"
  version = "1.0.4"

[[constraint]]
  name = "github.com/hashicorp/golang-lru"
  version = "0.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/mwitkow/grpc-proxy"
