[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "1.0.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[constraint]]
  name = "github.com/google/go-github"
  version = "15.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/gregjones/httpcache"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.4.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.13.0"

[[constraint]]
  name = "gopkg.in/bblfsh/sdk.v1"
  version = "1.16.0"

[[constraint]]
  name = "gopkg.in/sourcegraph/go-vcsurl.v1"
  version = "1.0.0"

[[constraint]]
  name = "gopkg.in/src-d/go-errors.v1"
  version = "1.0.0"

[[constraint]]
  name = "gopkg.in/src-d/go-git-fixtures.v3"
  version = "3.1.0"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.4.1"

[[constraint]]
  name = "gopkg.in/src-d/go-log.v1"
  version = "1.0.1"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

  [[prune.project]]
    name = "gopkg.in/src-d/go-git-fixtures.v3"
    non-go = false